version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test

      - run: gradle build

      - add_ssh_keys:
          fingerprints:
            - "85:7e:9e:e4:27:8e:85:74:17:67:b3:94:3b:b0:79:19"

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no sprayer-bot@sprayer-bot.euro2.ee /bin/mkdir /opt/sprayer-bot/builds/"${CIRCLE_BUILD_NUM}"
              scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r  build/libs/* sprayer-bot@sprayer-bot.euro2.ee:/opt/sprayer-bot/builds/"${CIRCLE_BUILD_NUM}"/
              echo "cd /opt/sprayer-bot && /bin/ln -sf builds/"${CIRCLE_BUILD_NUM}"/*.jar sprayer-bot-latest.jar" | ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no sprayer-bot@sprayer-bot.euro2.ee
              ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no sprayer-bot@sprayer-bot.euro2.ee sudo /bin/systemctl restart sprayer-bot
            fi
